- .travis/build.sh
- .travis/install.sh
- README.md
- cmake/Dependencies.cmake
- gloo/test/CMakeLists.txt
We can assume it is either installed on the system, or is built as part
of an upstream CMake project and defines the gtest target.
This change also prefixes the test binaries with "gloo_" to avoid
conflicts with the special CMake target name "test".
> Remove googletest submodule

- .github/workflows/build_linux.yaml
- CMakeLists.txt
- gloo/test/CMakeLists.txt
- gloo/test/broadcast_test.cc
1. Update libuv version
2. Install openssl 1.1
Gloo is currently pinned to openssl 1.1.
See: gloo/test/CMakeLists.txt
It has:
find_package(OpenSSL 1.1 REQUIRED EXACT)
3. Build with c++17 to resolve libuv errors.
4. Always install libssl-dev
5. Add LD_LIBRARY_PATH for runners
6.  SSL max limit is 512M - 1
Also, make a small change to one of the tests.
SSL max limit is 512M - 1 byte
broadcast test fails at 512M, passes with 1 less byte.
TODO: comment where this limit is coming from.
> Add CI for building on linux

- gloo/common/utils.cc
- gloo/common/utils.h
- gloo/transport/tcp/context.cc
- gloo/transport/tcp/context.h
- gloo/transport/tcp/device.cc
- gloo/transport/tcp/device.h
- gloo/transport/tcp/listener.cc
- gloo/transport/tcp/listener.h
- gloo/transport/tcp/pair.cc
- gloo/transport/tcp/pair.h
Summary:
All credit goes to original author XilunWu. I am just landing the code to unblock large training jobs.
D45740631 reduces gloo rendezvous cost for TCP backend by eliminating duplicate address publishing to TCPStore. Ben suggested "have seq_number == global_rank" to further get rid of `seq_number` exchange and Shawn reported why this didn't work. This diff serves a starting point for benchmarking the benefit of doing so ([testbed record](https://docs.google.com/document/d/1_p390fx0IiaZWbt-Dkdvp9jSgCKebiuG8_a6BVjHtMU/edit) shows 2x speedup: 46 min ProcessGroupGloo init time on 8k ranks -> 20 min).
The feature will be enabled via env variable (GLOO_ENABLE_RANK_AS_SEQUENCE_NUMBER) disabled by default that will be controlled by justKnobs.
Reviewed By: XilunWu
Differential Revision: …
> allow seq_number == global_rank for TCP backend

- gloo/common/store.h
- gloo/common/utils.cc
- gloo/common/utils.h
- gloo/transport/tcp/context.cc
- gloo/transport/tcp/listener.cc
Summary:
The TCP store has API v2 support we can reduce the network overhead of Gloo rendezvous significantly by fetching a batch of key instead of doing them one by one.
Initial testing shows ~15X improvement for 4k jobs.
Gloo process group init:
Baseline ( fbcode trunk):
2k job (https://fburl.com/mlhub/x1prxu89) : ~82sec (~1.4 min)
4k job (https://fburl.com/mlhub/v1djk4n5) : ~393 sec (~6.6min)
8k job (https://fburl.com/mlhub/cagqrs7m): (~55mins)
With optimizations (D48130088 + D52083376):
2k job (https://fburl.com/mlhub/x0cskdag)  : ~18 sec ( ~5x faster)
4k job (https://fburl.com/mlhub/xzmvkm4j) : ~ 25 sec (~15x faster)
8k job (https://fburl.com/mlhub/gdyeizv9)   : ~ 85 sec (~35x faster)
Reviewed By: xunnanxu
Differential Revision:
D52083376
Privacy Context Container: L1156430
> Use multi_get for store that has extended API support.

- .github/workflows/build-windows.yml
- .github/workflows/super-linter.yml
- gloo/allreduce_bcube.h
- gloo/test/base_test.cc
- gloo/test/base_test.h
Summary:
Add .clang-format 
Copied from https://github.com/pytorch/pytorch/blob/main/.clang-format
Reviewed By: wconstab, fduwjj
Differential Revision: D69275930
Pulled By: c-p-i-o
> Formatting changes + fix windows OSS build (#406)

- gloo/transport/tcp/device.h
- gloo/transport/tcp/error.h
- gloo/transport/tcp/listener.h
- gloo/transport/tcp/pair.cc
- gloo/transport/tcp/pair.h
Summary:
This fixes the Gloo TCP transport error handling so errors don't accidentally get casted to `Error` which results in a `no error` message on connection errors.
```
terminate called after throwing an instance of 'std::runtime_error'
what():  [fbcode/gloo/transport/tcp/pair.cc:147] no error
```
Differential Revision: D70212634
> gloo: fix error what

- gloo/common/logging.h
- gloo/common/utils.cc
- gloo/common/utils.h
- gloo/test/CMakeLists.txt
- gloo/test/tcp_test.cc
- gloo/transport/tcp/CMakeLists.txt
- gloo/transport/tcp/address.cc
- gloo/transport/tcp/address.h
- gloo/transport/tcp/device.cc
- gloo/transport/tcp/error.cc
- gloo/transport/tcp/error.h
- gloo/transport/tcp/helpers.cc
- gloo/transport/tcp/helpers.h
Summary: This adds connection retries to Gloo in order to try and mitigate issues related to connection timeouts.
Differential Revision: D70345714
> gloo: add connection retries

- gloo/cuda_allreduce_halving_doubling.h
- gloo/cuda_broadcast_one_to_all.h
Summary:
`nullptr` is preferable to `0` or `NULL`. Let's use it everywhere so we can enable `-Wzero-as-null-pointer-constant`.
- If you approve of this diff, please use the "Accept & Ship" button :-)
Reviewed By: dtolnay
Differential Revision: D70818154
> Use `nullptr` in gloo/cuda_allreduce_halving_doubling.h

- gloo/cuda_broadcast_one_to_all.h
Summary:
`nullptr` is typesafe. `0` and `NULL` are not. In the future, only `nullptr` will be allowed.
This diff helps us embrace the future _now_ in service of enabling `-Wzero-as-null-pointer-constant`.
Differential Revision: D71284808
> Fix deprecated use of 0/NULL in gloo/cuda_broadcast_one_to_all.h + 1

- gloo/test/tcp_test.cc
- gloo/transport/tcp/device.cc
- gloo/transport/tcp/helpers.cc
- gloo/transport/tcp/helpers.h
- gloo/transport/tcp/listener.cc
- gloo/transport/tcp/listener.h
- gloo/transport/tcp/loop.cc
- gloo/transport/tcp/loop.h
- gloo/transport/tcp/pair.cc
- gloo/transport/tcp/pair.h
Summary:
This overhauls how we schedule async operations on the tcp Loop. 
These changes greatly simplifies the memory management and simplifies the shutdown logic since memory ownership is better tied to epoll usage and relies less on shared_ptr copies everywhere to work around it.
This makes a few major changes:
* adds a new `registerDescriptor` method to Loop that provides a shared_ptr. This method will track the lifetime of the provided Handler and will release it when the epoll handle is updated/deleted.
* Make `Handler::handleEvents` signature provide a `Loop&` reference so all objects don't need to hold a shared_ptr to the loop.
* Update `helpers.h` to not manage it's own lifetime (instead using registerDescriptor shared_ptr support) and also not hold a shared_ptr to `Loop`.
* …
> gloo/transport/tcp/loop: better memory management and shutdown

- gloo/benchmark/runner.cc
- gloo/common/store.h
- gloo/examples/example1.cc
- gloo/rendezvous/context.cc
- gloo/rendezvous/context.h
- gloo/rendezvous/prefix_store.cc
- gloo/rendezvous/prefix_store.h
- gloo/test/base_test.h
- gloo/test/multiproc_test.h
- gloo/transport/context.cc
- gloo/transport/context.h
- gloo/transport/tcp/context.cc
- gloo/transport/tcp/context.h
Summary:
This modifies `connectFullMesh` to take in a shared_ptr<IStore> instead of a reference. This is an API breaking change but fairly easy to work around.
To have backwards compatibility in PyTorch during the commit phase we add a new ifdef `GLOO_SHARED_STORE` which can provide backwards compatibility until we update the pinned Gloo version in pytorch OSS repo.
This also adds a new `wait_get` method to `IStore` which will allow us to do a more efficient operation in PyTorch TCPStore. PyTorch's `Store::get` automatically waits so we want to make sure we can avoid waiting twice to reduce network traffic.
This change will land simultaneously in PyTorch and Gloo repos.
Differential Revision: D72084111
> gloo: use shared Stores

- gloo/test/allgather_test.cc
- gloo/test/allgatherv_test.cc
- gloo/test/allreduce_test.cc
- gloo/test/barrier_test.cc
- gloo/test/base_test.cc
- gloo/test/base_test.h
- gloo/test/broadcast_test.cc
- gloo/test/gather_test.cc
- gloo/test/gatherv_test.cc
- gloo/test/multiproc_test.h
- gloo/test/reduce_test.cc
- gloo/test/scatter_test.cc
- gloo/test/tcp_test.cc
- gloo/transport/tcp/context.cc
- gloo/transport/tcp/context.h
- gloo/transport/tcp/device.cc
- gloo/transport/tcp/device.h
- gloo/transport/tcp/helpers.h
- gloo/transport/tcp/listener.cc
- gloo/transport/tcp/listener.h
- gloo/transport/tcp/pair.cc
- gloo/transport/tcp/pair.h
- gloo/transport/tcp/socket.cc
- gloo/transport/tcp/socket.h
- gloo/transport/tcp/tls/device.cc
- gloo/transport/tcp/tls/pair.cc
- gloo/transport/tcp/tls/pair.h
Summary:
Original commit changeset: 4cfad1d7b700
Original Phabricator Diff: D69698406
***
gloo: only shutdown device when async
See original PR for details and test plan: D69698406
This extends that PR with one small change to avoid shutting down Device when using non-async mode to preserve backwards compatibility for caffe2.
Reviewed By: fduwjj
Differential Revision: D72425729
> Back out "Revert D69698406: gloo: async lazy connect"

- gloo/transport/tcp/context.cc
- gloo/transport/tcp/context.h
When multiple operations are running we may end up calling `getPair` from multiple threads simultaneously. This causes a crash due to duplicate connect calls and state modifications.
This does add an additional synchronization point but under most usage this should be very cheap as after the first connection we only check a single variable and return.
Test plan:
https://github.com/pytorch/pytorch/pull/150801
> tcp/context: use mutex to avoid race condition when multiple operations are running

- gloo/common/utils.cc
getenv can't be found on MacOS Apple Silicon.
> Fix missing header for getenv

- gloo/transport/tcp/device.cc
Summary:
Function `getaddrinfo()` is expected to return 0 on success and other error codes in case of failures as per the man page: https://fburl.com/tg3q11nw. However, current logic in `lookupAddrForHostname()` function is just checking for return value not equal to -1: https://fburl.com/code/wk7ztua9 for error check.This fix ensures that the return value of `getaddrinfo()` zero on suceessfull cases.
{F1977470144}
Differential Revision: D73746837
> Doing the proper error check after calling getaddrinfo

- gloo/barrier_all_to_all.h
- gloo/barrier_all_to_one.h
- gloo/broadcast_one_to_all.h
Summary:
This makes barrier and broadcast operations in Gloo use UnboundBuffer instead of Buffer. UnboundBuffer is the newer preferred buffer implementation and also makes the algorithms much easier to express/understand and efficient since we don't need to allocate more memory.
Tracking issue for Buffer removal: https://github.com/pytorch/gloo/issues/432
Differential Revision: D74096980
> gloo: use unbound buffers for barrier, broadcast

- gloo/transport/ibverbs/device.cc
Summary: This is needed so we can detect whether the Gloo backend can do direct communication with the GPU or if we need to transfer them to CPU before doing accelerate collectives.
Differential Revision: D74495060
> gloo/ibverbs: enable gpudirect with new nvidia drivers

- gloo/test/CMakeLists.txt
Enable building of gloo_test without requiring OpenSSL to be present. If OpenSSL is not present, SSL/TLS related tests are not linked. If OpenSSL is present, then TLS tests are compiled and linked.
> remove OpenSSL requirement for testing

- .clang-format
- .github/config/lint/.clang-format
- .github/workflows/super-linter.yml
- gloo/allreduce_bcube.h
- gloo/alltoallv.h
- gloo/common/string.h
- gloo/cuda_allreduce_bcube.h
- gloo/math.h
- gloo/test/base_test.h
- gloo/transport/ibverbs/pair.cc
- gloo/transport/ibverbs/pair.h
- gloo/transport/pair.h
- gloo/transport/tcp/pair.cc
- gloo/transport/tcp/pair.h
- gloo/transport/uv/libuv.h
- gloo/transport/uv/pair.h
55b6bf777b68a9c36b7034ca615411cb8d0cab15 applied clang-format to the codebase, but did not add the configuration file used. This change adds the configuration file, `.clang-format`, and applies clang-format to the codebase. The configuration file is imported from [PyTorch](https://github.com/pytorch/pytorch), with attribution in comments at the beginning of the file.
The config file used seems to line up well with the one used for 55b6bf777b68a9c36b7034ca615411cb8d0cab15, as the diff generated is relatively small. Having the config available will enable contributions going forward to use consistent formatting and avoid having to apply it across the whole codebase again.
To further this aim, I have linked the `.clang-format` into `.github/config/lint`, to enable the `lint` job in CI to …
> Add .clang-format config, provide to super-linter, and apply formatting to codebase

- gloo/context.h
- gloo/test/CMakeLists.txt
- gloo/test/base_test.cc
- gloo/test/base_test.h
- gloo/test/remote_key_test.cc
- gloo/transport/CMakeLists.txt
- gloo/transport/context.h
- gloo/transport/ibverbs/CMakeLists.txt
- gloo/transport/ibverbs/context.cc
- gloo/transport/ibverbs/context.h
- gloo/transport/ibverbs/pair.cc
- gloo/transport/ibverbs/pair.h
- gloo/transport/ibverbs/remote_key.cc
- gloo/transport/ibverbs/remote_key.h
- gloo/transport/ibverbs/unbound_buffer.cc
- gloo/transport/ibverbs/unbound_buffer.h
- gloo/transport/pair.h
- gloo/transport/remote_key.h
- gloo/transport/unbound_buffer.h
Differential Revision: D75919074
> gloo/ibverbs: support put/get operations

- gloo/transport/tcp/pair.cc
Summary:
Improve error messages in the TCP transport when a collective mismatch occurs. Right now it throws a mysterious error such as:
```
gloo::EnforceNotMet: [enforce fail at fbcode/gloo/transport/tcp/pair.cc:456] op.preamble.length <= op.nbytes. 194478720 vs 4
```
This updates the error message to indicate that it's a size mismatch and likely due to a bug in the user code.
Meta:
User post: gloo::EnforceNotMet: [enforce fail at fbcode/gloo/transport/tcp/pair.cc:456] op.preamble.length <= op.nbytes. 194478720 vs 4
Differential Revision: D78377800
> gloo/tcp: better error message on collective mismatch

- gloo/types.h
fixes unknown type name compile errors.
clang-format'ed version of #448
> gloo/types.h: include cstdint
